"""Add is_seen to PatientRequest

Revision ID: 0da34209246d
Revises: de10f9f4c304
Create Date: 2025-11-22 00:25:45.332578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da34209246d'
down_revision = 'de10f9f4c304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seen', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_request', schema=None) as batch_op:
        batch_op.drop_column('is_seen')

    # ### end Alembic commands ###
