"""Add visit_id to LabRequest

Revision ID: 5b52e1b2cdfc
Revises: f3cbdf60050b
Create Date: 2025-10-26 18:33:13.038958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b52e1b2cdfc'
down_revision = 'f3cbdf60050b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'lab_visit', ['visit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visit_id')

    # ### end Alembic commands ###
