"""Add columns

Revision ID: 7fe2bc39cf03
Revises: 0da34209246d
Create Date: 2025-11-22 00:59:21.645012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe2bc39cf03'
down_revision = '0da34209246d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('admin_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_request', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('admin_note')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
