"""initial migration

Revision ID: f0210ef0b76d
Revises: 
Create Date: 2025-09-22 22:37:37.776698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0210ef0b76d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mother_name', sa.String(length=120), nullable=False),
    sa.Column('mother_age', sa.Integer(), nullable=True),
    sa.Column('nhis_status', sa.String(length=20), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_time', sa.Time(), nullable=True),
    sa.Column('delivery_type', sa.String(length=50), nullable=False),
    sa.Column('cs_indication', sa.String(length=255), nullable=True),
    sa.Column('baby_gender', sa.String(length=10), nullable=False),
    sa.Column('baby_weight', sa.Float(), nullable=True),
    sa.Column('mother_condition', sa.String(length=255), nullable=True),
    sa.Column('baby_condition', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('brand_name', sa.String(length=256), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('unit_cost_price', sa.Float(), nullable=False),
    sa.Column('unit_selling_price', sa.Float(), nullable=False),
    sa.Column('quantity_left', sa.Integer(), nullable=False),
    sa.Column('quantity_supplied', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('dispensary_total', sa.Float(), nullable=True),
    sa.Column('laboratory_total', sa.Float(), nullable=True),
    sa.Column('hmos_total', sa.Float(), nullable=True),
    sa.Column('total_income', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_date')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_number', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('middle_name', sa.String(length=120), nullable=True),
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('Male', 'Female', 'Other', name='sexenum'), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('nhis_status', sa.Enum('NHIS', 'NON_NHIS', name='nhisstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_hospital_number'), ['hospital_number'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('date_of_employment', sa.Date(), nullable=False),
    sa.Column('office_location', sa.String(length=150), nullable=True),
    sa.Column('position', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('schools_attended', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dispense_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('quantity_dispensed', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('dispensed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finance_record_id', sa.Integer(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finance_record_id'], ['finance_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hmo_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hmo_name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['finance_id'], ['finance_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inpatients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('hospital_number', sa.String(length=50), nullable=True),
    sa.Column('patient_name', sa.String(length=256), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('medications_given', sa.Text(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('discharge', sa.Boolean(), nullable=True),
    sa.Column('referred', sa.Boolean(), nullable=True),
    sa.Column('rip', sa.Boolean(), nullable=True),
    sa.Column('admitted_at', sa.DateTime(), nullable=True),
    sa.Column('discharged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(length=120), nullable=True),
    sa.Column('patient_surname', sa.String(length=120), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('nhis_status', sa.String(length=20), nullable=True),
    sa.Column('inpatient_status', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('sample', sa.String(length=120), nullable=True),
    sa.Column('referring_physician', sa.String(length=120), nullable=True),
    sa.Column('laboratory_number', sa.String(length=50), nullable=True),
    sa.Column('investigations', sa.Text(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('laboratory_number')
    )
    op.create_table('operation_diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=256), nullable=False),
    sa.Column('surname', sa.String(length=256), server_default='Unknown', nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_sex', sa.String(length=10), nullable=False),
    sa.Column('hospital_number', sa.String(length=64), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('surgery_done', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('estimated_blood_loss', sa.String(length=64), nullable=True),
    sa.Column('anesthesia_type', sa.String(length=128), nullable=True),
    sa.Column('surgeon_name', sa.String(length=256), nullable=True),
    sa.Column('assistant_name', sa.String(length=256), nullable=True),
    sa.Column('anaesthetist_name', sa.String(length=256), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('post_op_condition', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outpatients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(length=256), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('medications_given', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('nhis_status', sa.String(length=20), nullable=False),
    sa.Column('visited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outpatients')
    op.drop_table('operation_diary')
    op.drop_table('lab_visit')
    op.drop_table('inpatients')
    op.drop_table('hmo_payments')
    op.drop_table('finance_logs')
    op.drop_table('dispense_records')
    op.drop_table('users')
    op.drop_table('staff')
    op.drop_table('roles')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_hospital_number'))

    op.drop_table('patients')
    op.drop_table('finance_records')
    op.drop_table('drugs')
    op.drop_table('deliveries')
    # ### end Alembic commands ###
