"""Add status column to LabRequest

Revision ID: f3cbdf60050b
Revises: 110c2eb35e67
Create Date: 2025-10-13 07:59:11.103815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cbdf60050b'
down_revision = '110c2eb35e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_requests', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
