"""Add age column to patients table

Revision ID: f877f19e224a
Revises: a7bd6b63d2cc
Create Date: 2025-11-04 15:03:58.928439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f877f19e224a'
down_revision = 'a7bd6b63d2cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family_history')
    op.drop_table('vital_signs')
    op.drop_table('immunizations')
    op.drop_table('allergies')
    op.drop_table('medical_history')
    op.drop_table('social_history')
    with op.batch_alter_table('patient_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['patient_id'])
        batch_op.drop_constraint(batch_op.f('patient_cards_patient_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'])
        batch_op.drop_column('height')
        batch_op.drop_column('blood_pressure')
        batch_op.drop_column('bmi')
        batch_op.drop_column('examination')
        batch_op.drop_column('investigations')
        batch_op.drop_column('imaging_results')
        batch_op.drop_column('allergies')
        batch_op.drop_column('respiratory_rate')
        batch_op.drop_column('medications')
        batch_op.drop_column('heart_rate')
        batch_op.drop_column('history_of_present_illness')
        batch_op.drop_column('past_medical_history')
        batch_op.drop_column('temperature')
        batch_op.drop_column('plan')
        batch_op.drop_column('oxygen_saturation')
        batch_op.drop_column('weight')
        batch_op.drop_column('assessment')
        batch_op.drop_column('created_at')
        batch_op.drop_column('chief_complaint')
        batch_op.drop_column('lab_results')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.drop_column('marital_status')
        batch_op.drop_column('next_of_kin_relationship')
        batch_op.drop_column('next_of_kin_name')
        batch_op.drop_column('religion')
        batch_op.drop_column('email')
        batch_op.drop_column('occupation')
        batch_op.drop_column('next_of_kin_phone')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('religion', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_relationship', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('age')

    with op.batch_alter_table('patient_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_results', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('chief_complaint', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('assessment', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('oxygen_saturation', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('plan', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('past_medical_history', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('history_of_present_illness', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('heart_rate', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('medications', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('respiratory_rate', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('imaging_results', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('investigations', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('examination', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bmi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('blood_pressure', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('patient_cards_patient_id_fkey'), 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('notes')

    op.create_table('social_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('smoking', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('alcohol', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('drug_use', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('marital_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('living_conditions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('social_history_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('social_history_pkey'))
    )
    op.create_table('medical_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chronic_conditions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('past_surgeries', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_medications', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('immunizations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blood_group', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('genotype', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('medical_history_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('medical_history_pkey'))
    )
    op.create_table('allergies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('allergen', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('reaction', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date_identified', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('allergies_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('allergies_pkey'))
    )
    op.create_table('immunizations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vaccine_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('date_administered', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('next_due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('administered_by', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('immunizations_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('immunizations_pkey'))
    )
    op.create_table('vital_signs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_recorded', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('blood_pressure', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('heart_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('respiratory_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('vital_signs_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vital_signs_pkey'))
    )
    op.create_table('family_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diabetes', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hypertension', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cancer', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sickle_cell', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('other_conditions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('family_history_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('family_history_pkey'))
    )
    # ### end Alembic commands ###
